### ISSUE TITLE
Bug regarding deployment in Heroku

### ISSUE THREAD

**Issue by UO266499** [Arquisoft/radarin_en1b#52] opened 2021-02-23 10:57 UTC
Error when deploying the app in heroku regarding graphviz:

Error: Command failed: heroku container:push web --app radarinen1bwebapp --arg API_URI="https://radarinen1brestapi.herokuapp.com/api" › Warning: heroku update available from 7.47.12 to 7.47.13. The command '/bin/sh -c apt install graphviz' returned a non-zero code: 1 ▸ Error: docker build exited with Error: 1

**Comment by pglez82** [comment] 2021-02-23 12:39
Duplicate of #53

**Closed as completed** 2021-02-23 14:51 UTC
Labels: bug
